/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyConnection */

#ifndef _Included_MyConnection
#define _Included_MyConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyConnection
 * Method:    createStat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_MyConnection_createStat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
