/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyDriver */

#ifndef _Included_MyDriver
#define _Included_MyDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyDriver
 * Method:    getConn
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_MyDriver_getConn
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

