/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyResultSet */

#ifndef _Included_MyResultSet
#define _Included_MyResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyResultSet
 * Method:    nxt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_MyResultSet_nxt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     MyResultSet
 * Method:    getI
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_MyResultSet_getI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     MyResultSet
 * Method:    getS
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyResultSet_getS
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
