/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyStatement */

#ifndef _Included_MyStatement
#define _Included_MyStatement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyStatement
 * Method:    exeQuery
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_MyStatement_exeQuery
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
